import { Location } from "./location.model"
import { Service } from "./service.model"

export interface User {
    location: Location,
    firstname: string,
    lastname: string,
    birthDate: string,
    gender: string,
    cin: number,
    city: string,
    allergie: string,
    email: string,
    postal: number,
    role: string,
    phoneVerified: boolean,
    emailVerified: boolean,
    online: boolean,
    etat: string,
    prestataire: boolean,
    Validate_diplome?: boolean,
    age: number,
    Information_medicale?: string,
    occupe: boolean,
    experience?: number ,
    actualFunction?: string,
    companyName?:string ,
    companyAdress?: string,
    tva?: string,
    ableToDo?: boolean,
    expireDate: string,
    banLiftTime: string,
    institution?: string ,
    _id: string,
    phoneNumber: number,
    address: string,
    cin_Pics?: string,
    service?: Service[],
    createdAt: string,
    updatedAt: string,
    lastLogin?: string,
    om_Pic ?: {
        path : string,
    }[]
  }