import { environment } from 'src/environments/environment';

// const BASE_URL = environment.baseURL;
const BASE_URL = environment.baseIP;


    export const  CREATE_PARAMETER_API                     = BASE_URL + '/api/parameter/post-parameter'; // {}
    export const  GET_PARAMETER_API                        = BASE_URL + '/api/parameter/parameter';
    export const  GET_NEW_TOKEN_API                        = BASE_URL + '/api/auth/refresh-token/';
    export const  GET_PARAMETER_BY_NAME_API                = BASE_URL + '/api/parameter/ParameterByName'; // /api/parameter/ParameterByName/{name}
    export const  DELETE_PARAMETER_API                     = BASE_URL + '/api/parameter/delete-parameter'; // /api/parameter/delete-parameter/{name}
    export const  UPDATE_PARAMETER_API                     = BASE_URL + '/api/parameter/update-parameter'; // /api/parameter/update-parameter/{name}
    export const  REGISTER_API                             = BASE_URL + '/api/auth/register'; // {}
    export const  VERIFY_OTP_API                           = BASE_URL + '/api/auth/verify-otp'; // {}
    export const  EMAIL_VERIFICATION_API                   = BASE_URL + '/api/auth/email-verification'; // {}
    export const  LOGIN_API                                = BASE_URL + '/api/auth/login'; // {}
    export const  SEND_OTP_API                             = BASE_URL + '/api/user/check-new-phone-number'; // {}
    export const  FORGOT_PASSWORD_EMAIL_API                = BASE_URL + '/api/auth/forgot-password-email'; // {}
    export const  RESET_PASSWORD_EMAIL_API                 = BASE_URL + '/api/auth/reset-password-email'; // /api/auth/reset-password-email/{userId}/{token}
    export const  DESACTIVATE_ACCOUNT_API                  = BASE_URL + '/api/user/desactive-me'; // {}
    export const  DELETE_ACCOUNT_API                       = BASE_URL + '/api/user/delete-account'; // {}
    export const  GET_INFORMATION_API                      = BASE_URL + '/api/user/my-infor'; // {}
    export const  CHANGE_PASSWORD_API                      = BASE_URL + '/api/user/change-password'; // {}
    export const  UPDATE_PROFILE_API                       = BASE_URL + '/api/user/update-profile'; // {}
    export const  GET_PRICE_API                            = BASE_URL + '/api/user/prix_demande'; // /api/user/prix_demande/{id}
    export const  GET_INFORMATION_BY_ID_API                = BASE_URL + '/api/user/infor-by-id/'; // /api/user/infor-by-id/{id}
    export const  ADMIN_DELETE_ACCOUNT_API                 = BASE_URL + '/api/user/admin-delete-account'; // /api/user/admin-delete-account/{id}
    export const  GET_ALL_INFORMATION_API                  = BASE_URL + '/api/user/all-infor'; // /api/user/all-infor
    export const  COUNT_ALL_USERS_API                      = BASE_URL + '/api/user/count-all-users'; // /api/user/count-all-users
    export const  GET_ALL_PREST_INFORMATION_API            = BASE_URL + '/api/user/all-prest-infor'; // /api/user/all-prest-infor
    export const  DESACTIVE_USER_API                       = BASE_URL + '/api/user/desactive-user'; // /api/user/desactive-user/{id}
    export const  BLOCAGE_USER_API                         = BASE_URL + '/api/user/blocage-user'; // /api/user/blocage-user/{id}
    export const  ACTIVE_USER_API                          = BASE_URL + '/api/user/active-user'; // /api/user/active-user/{id}
    export const  VALIDATE_DIPLOME_API                     = BASE_URL + '/api/user/validate-diplome'; // /api/user/validate-diplome/{id}
    export const  ADMIN_UPDATE_PROFILE_API                 = BASE_URL + '/api/user/admin-update-profile'; // /api/user/admin-update-profile/{id}
    export const  GET_POPULARITY_PREST_API                 = BASE_URL + '/api/user/popularityPrest'; // /api/user/popularityPrest
    export const  GET_POPULARITY_USER_API                  = BASE_URL + '/api/user/popularityUser'; // /api/user/popularityUser
    export const  GET_ALL_PRESTATAIRE_API                  = BASE_URL + '/api/prestataire/get-all-prestataire'; // /api/prestataire/get-all-prestataire
    export const  GET_ALL_DEMANDE_PREST_API                = BASE_URL + '/api/demandePrestataire/allDemandePrest'; // /api/demandePrestataire/allDemandePrest
    export const  COUNT_ALL_DEMANDE_SUCCESS_API            = BASE_URL + '/api/demandePrestataire/CountallDemandeSuccess'; // /api/demandePrestataire/CountallDemandeSuccess
    export const  COUNT_BY_TYPE_API                        = BASE_URL + '/api/demandePrestataire/CountByType'; // /api/demandePrestataire/CountByType
    export const  COUNT_ALL_DEMANDE_IGNORED_API            = BASE_URL + '/api/demandePrestataire/CountallDemandeIgnored'; // /api/demandePrestataire/CountallDemandeIgnored
    export const  COUNT_ALL_DEMANDE_PROCHE_API             = BASE_URL + '/api/demandePrestataire/CountAllDemandProcheAndMedecinTraiteur'; // /api/demandePrestataire/CountAllDemandProcheAndMedecinTraiteur
    export const  COUNT_ALL_SELF_DEMANDE_API               = BASE_URL + '/api/demandePrestataire/countAllSelfdemand'; // /api/demandePrestataire/countAllSelfdemand
    export const  DEMAND_STATE_API                         = BASE_URL + '/api/demandePrestataire/demandState'; // /api/demandePrestataire/demandState
    export const  COUNT_NEW_PREST_API                      = BASE_URL + '/api/demandePrestataire/CountNewPrest'; // /api/demandePrestataire/CountNewPrest
    export const  GET_ALL_RECEIVED_DEMANDS_API             = BASE_URL + '/api/demandePrestataire/allReceivedDemands'; // /api/demandePrestataire/allReceivedDemands
    export const  GET_ALL_SENT_DEMANDS_API                 = BASE_URL + '/api/demandePrestataire/allSentDemands'; // /api/demandePrestataire/allSentDemands
    export const  GET_SPECIALITIES_API                     = BASE_URL + '/api/speciality/specialities'; // /api/speciality/specialities
    export const  GET_SPECIALITY_BY_ID_API                 = BASE_URL + '/api/speciality/speciality/{id}'; // /api/speciality/speciality/{id}
    export const  CREATE_SPECIALITY_API                    = BASE_URL + '/api/speciality/post-speciality'; // /api/speciality/post-speciality
    export const  UPDATE_POST_SPECIFIED_FIELD_API          = BASE_URL + '/api/speciality/post-specifiedField'; // /api/speciality/post-specifiedField
    export const  UPDATE_POST_SPECIFIED_TYPE_API           = BASE_URL + '/api/speciality/post-specifiedType'; // /api/speciality/post-specifiedType/{idSpeciality}/{idSpecifiedField}/{idTypeSpecifiedField}
    export const  DELETE_SPECIALITY_API                    = BASE_URL + '/api/speciality/delete-speciality'; // /api/speciality/delete-speciality
    export const  DELETE_SPECIFIED_FIELD_API               = BASE_URL + '/api/speciality/delete-specifiedField'; // /api/speciality/delete-specifiedField
    export const  DELETE_SPECIFIED_TYPE_API                = BASE_URL + '/api/speciality/delete-specifiedType'; // /api/speciality/delete-specifiedType
    export const  UPDATE_SPECIALITY_API                    = BASE_URL + '/api/speciality/update-speciality'; // /api/speciality/update-speciality/{id}
    export const  UPDATE_SPECIFIED_FIELD_API               = BASE_URL + '/api/speciality/update-specifiedField'; // /api/speciality/update-specifiedField/{idSpeciality}/{idSpecifiedField}
    export const  UPDATE_SPECIFIED_TYPE_API                = BASE_URL + '/api/speciality/update-specifiedType'; // /api/speciality/update-specifiedType/{idSpeciality}/{idSpecifiedField}/{idTypeSpecifiedField}/{idSpecifiedType}
    export const  INJECT_SPECIALITIES_API                  = BASE_URL + '/api/speciality/inject-specialities'; // /api/speciality/inject-specialities
    export const  CREATE_TESTIMONY_API                     = BASE_URL + '/api/testimony/post-testimony'; // /api/testimony/post-testimony
    export const  GET_TESTIMONIES_API                      = BASE_URL + '/api/testimony/testimonies'; // /api/testimony/testimonies
    export const  GET_TESTIMONIES_BY_USER_ID_API           = BASE_URL + '/api/testimony/TestimoniesByUserId'; // /api/testimony/TestimoniesByUserId/{userId}
    export const  UPDATE_TESTIMONY_API                     = BASE_URL + '/api/testimony/update-Testimony'; // /api/testimony/update-Testimony/{id}
    export const  CREATE_MEMBER_API                        = BASE_URL + '/api/member/post-member'; // /api/member/post-member
    export const  GET_MEMBERS_API                          = BASE_URL + '/api/member/members'; // /api/member/members
    export const  GET_MEMBER_BY_ID_API                     = BASE_URL + '/api/member/MemberById'; // /api/member/MemberById/{id}
    export const  GET_MEMBERS_BY_USER_ID_API               = BASE_URL + '/api/member/MembersByUserId'; // /api/member/MembersByUserId/{userId}
    export const  DELETE_MEMBER_API                        = BASE_URL + '/api/member/delete-Member'; // /api/member/delete-Member/{id}
    export const  UPDATE_MEMBER_API                        = BASE_URL + '/api/member/update-Member'; // /api/member/update-Member/{id}
    export const  GET_ALL_SOS_API                          = BASE_URL + '/api/sos/allSos'; // /api/sos/allSos
    export const  CREATE_AVIS_API                          = BASE_URL + '/api/avis/post-avis'; // /api/avis/post-avis/{demandId}/{targetId}
    export const  GET_AVIS_API                             = BASE_URL + '/api/avis/avis'; // /api/avis/avis
    export const  GET_AVIS_BY_ID_API                       = BASE_URL + '/api/avis/AvisById'; // /api/avis/AvisById/{id}
    export const  GET_AVIS_BY_USER_ID_API                  = BASE_URL + '/api/avis/AvisByUserId'; // /api/avis/AvisByUserId/{userId}
    export const  DELETE_AVIS_API                          = BASE_URL + '/api/avis/delete-avis'; // /api/avis/delete-avis/{id}
    export const  UPDATE_AVIS_API                          = BASE_URL + '/api/avis/update-avis'; // /api/avis/update-avis/{id}
    export const  ADD_SUBSCRIPTION_API                     = BASE_URL + '/api/monetization/add-subscription'; // /api/monetization/add-subscription
    export const  GET_ALL_SUBSCRIPTION_API                 = BASE_URL + '/api/monetization/allsubscription'; // /api/monetization/allsubscription
    export const  GET_SUBSCRIPTION_BY_ID_API               = BASE_URL + '/api/monetization/subscriptionById'; // /api/monetization/subscriptionById/{id}
    export const  DELETE_SUBSCRIPTION_API                  = BASE_URL + '/api/monetization/delete-subscription'; // /api/monetization/delete-subscription/{id}
    export const  UPDATE_SUBSCRIPTION_API                  = BASE_URL + '/api/monetization/update-subscription'; // /api/monetization/update-subscription/{id}
    export const  UPDATE_SUBSCRIPTION_BY_USER_ID_API       = BASE_URL + '/api/monetization/subscriptionByUserId'; // /api/monetization/update-subscription/{id}
    export const  INJECT_SUBSCRIPTION_API                  = BASE_URL + '/api/monetization/inject-subscription'; // /api/monetization/inject-subscription
    export const  PURCHASE_API                             = BASE_URL + '/api/monetization/purchase'; // /api/monetization/purchase
    export const  GET_ALL_PURCHASES_API                    = BASE_URL + '/api/monetization/allPurchases'; // /api/monetization/allPurchases
    export const  GET_ALL_MY_PURCHASES_API                 = BASE_URL + '/api/monetization/allMyPurchases'; // /api/monetization/allMyPurchases
    export const  GET_ALL_INCOMES_API                      = BASE_URL + '/api/monetization/allIncomes'; // /api/monetization/allIncomes
    export const  GET_ALL_MY_INCOMES_API                   = BASE_URL + '/api/monetization/allMyIncomes'; // /api/monetization/allMyIncomes
    export const  GET_COUNT_SUBSCRIPTIONS_API              = BASE_URL + '/api/monetization/countSubscriptions'; // /api/monetization/countSubscri       p       tions
    export const  GET_FAMILY_MEMBER_INFO_API               = BASE_URL + '/api/member/MemberById'; // /api/member/familyMembers
    export const  GET_FAMILY_MEMBERS_BY_USER_ID_API        = BASE_URL + '/api/member/membersByUserId'; // /api/member/membersByUserId/{userId}
