import { FieldType } from '@shared/dynamicForm/FieldType';
import { DynamicForm } from '@shared/dynamicForm/dynamicform.config';

export const SIGN_UP_PRESTATAIRE_PARAMEDICAL: DynamicForm = {
  hasFiles: false,
  fields: [
    {
      type: FieldType.radiobuttons,
      disabled: false,
      name: 'type',
      label: '',
      value: '',
      placeholder: '',
      width: '100%',
      options: [
        'infirmier(e)',
        'Ausilisire de vie',
        'Aide soignante',
    
     
      ],
      mobileWidth: '100%',
      mobileOrder: 1,
      desktopOrder: 1,
      flex: {
        direction: 'row',
      },
    },
    {
      type: FieldType.radiobuttons,
      disabled: false,
      name: 'type',
      label: '',
      value: '',
      placeholder: '',
      width: '100%',
      options: [
        'Technicien de réanimation',
  
        'Kinésithérapeute',
      ],
      mobileWidth: '100%',
      mobileOrder: 2,
      desktopOrder: 2,
      flex: {
        direction: 'row',
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'firstname',
      label: 'Nom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 3,
      desktopOrder: 3,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'lastname',
      label: 'Prénom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 4,
      desktopOrder: 4,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },

    {
      type: FieldType.datepicker,
      disabled: false,
      name: 'birthDate',
      label: 'Date de naissance',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'phoneNumber',
      label: 'Numéro de téléphone',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 6,
      desktopOrder: 6,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'email',
      label: 'Adresse e-mail',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.singleselection,
      disabled: false,
      name: 'gender',
      label: 'Gendre',
      value: '',
      options: ['Male', 'Female', 'Other'],
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.numberbox,
      disabled: false,
      name: 'cin',
      label: 'Numéro CIN',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 9,
        maxLength: 9,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'address',
      label: 'Adresse',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'vile',
      label: 'Ville',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },
    
    {
      type: FieldType.input,
      disabled: false,
      name: 'postal',
      label: 'Code postal',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.singleselection,
      disabled: false,
      name: 'diplome',
      label: 'Diplome me',
      value: '',
      options: ['ING'],

      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 11,
      desktopOrder: 11,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'anne',
      label: 'Annees dexperance',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'photo',
      label: 'Photo',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'copiecin',
      label: 'copie scannee de CIN recto verso',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee comforme du  diplome ',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      activationFieldName: 'type',
      activationValue: 'Ausilisire de vie',
      type: FieldType.inputuploade,
      disabled: false,
      name: 'b3',
      label: 'copie scannee du bulletin N°3',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      activationFieldName: 'type',
      activationValue: 'Kinésithérapeute',
      type: FieldType.radiobuttons,
      disabled: false,
      name: 'inscritCnam',
      label: 'Etes vous inscrit dans l CNAM',
      value: '',
      placeholder: '',
      width: '100%',
      options: ['oui', 'non'],
      mobileWidth: '100%',
      mobileOrder: 1,
      desktopOrder: 1,
      flex: {
        direction: 'row',
      },
    },
    {
      type: FieldType.checkbox,
      disabled: false,
      name: 'conditions_generales',
      label: `Je reconnais avoir lu <a href=""> les conditions générales d'utilisation</a> et les accepte, <a href=""> la politique de protection</a> des données et consent au traitement de mes données dans le cadre du service`,
      value: false,
      successValue: true,
      failValue: false,
      width: '100%',
      mobileWidth: '100%',
      mobileOrder: 15,
      desktopOrder: 15,
      flex: {
        direction: 'row',
      },
    
    },
  ],
};

export const SIGN_UP_PRESTATAIRE_MEDECIN: DynamicForm = {
  hasFiles: false,
  fields: [
    {
      type: FieldType.radiobuttons,
      disabled: false,
      name: 'type',
      label: '',
      value: '',
      placeholder: '',
      width: '100%',
      options: ['Médecins Généralistes', 'Médecins Spécialistes', 'Pédiatre'],
      mobileWidth: '100%',
      mobileOrder: 1,
      desktopOrder: 1,
      flex: {
        direction: 'row',
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'firstname',
      label: 'Nom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 3,
      desktopOrder: 3,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'lastname',
      label: 'Prénom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 4,
      desktopOrder: 4,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },

    {
      type: FieldType.datepicker,
      disabled: false,
      name: 'birthDate',
      label: 'Date de naissance',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'phoneNumber',
      label: 'Numéro de téléphone',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 6,
      desktopOrder: 6,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'email',
      label: 'Adresse e-mail',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.singleselection,
      disabled: false,
      name: 'gender',
      label: 'Gendre',
      value: '',
      options: ['Male', 'Female', 'Other'],
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.numberbox,
      disabled: false,
      name: 'cin',
      label: 'Numéro CIN',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 9,
        maxLength: 9,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'ordre',
      label: `Indentifiant d l'ordre des médecinsordre`,
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'address',
      label: 'Adresse',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'vile',
      label: 'Ville',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'postal',
      label: 'Code postal',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      activationFieldName: 'type',
      activationValue: 'Médecins Spécialistes',
      type: FieldType.singleselection,
      disabled: false,
      name: 'specialty',
      label: 'Spécialité',
      value: '',
      options: [
        'Médecin physique',
        'Médecin géneraliste',
        'Médecin anti-douleur',
        'Médecin cardiologue',
        'Médecin neurologue',
        'Médecin pneumologue',
        'Médecin pédiatre',
      ],

      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 11,
      desktopOrder: 11,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'poste',
      label:
        'Poste actue! / dernier poste occupé | avec possibiité de plusieurs )',
      value: '',
      placeholder: '',
      width: '100%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'ecole',
      label: 'Ecole de formation (avec possibilité de plusieurs)',
      value: '',
      placeholder: '',
      width: '100%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'ecole',
      label: 'Années cexpériences',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'file name',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'copiecin',
      label: 'copie scannee de CIN recto verso',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee comforme du  diplome ',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
 
      type: FieldType.radiobuttons,
      disabled: false,
      name: 'inscritCnam',
      label: 'Etes vous inscrit dans l CNAM',
      value: '',
      placeholder: '',
      width: '100%',
      options: ['oui', 'non'],
      mobileWidth: '100%',
      mobileOrder: 1,
      desktopOrder: 1,
      flex: {
        direction: 'row',
      },
    },
    {
      type: FieldType.checkbox,
      disabled: false,
      name: 'conditions_generales',
      label: `Je reconnais avoir lu <a href=""> les conditions générales d'utilisation</a> et les accepte, <a href=""> la politique de protection</a> des données et consent au traitement de mes données dans le cadre du service`,
      value: false,
      successValue: true,
      failValue: false,
      width: '100%',
      mobileWidth: '100%',
      mobileOrder: 15,
      desktopOrder: 15,
      flex: {
        direction: 'row',
      },
   
    },
  ],
};
export const SIGN_UP_PRESTATAIRE_TRANSPORTMEDICAL: DynamicForm = {
  hasFiles: false,
  fields: [
    {
      type: FieldType.input,
      disabled: false,
      name: 'firstname',
      label: 'Nom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 3,
      desktopOrder: 3,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'lastname',
      label: 'Prénom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 4,
      desktopOrder: 4,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },

    {
      type: FieldType.datepicker,
      disabled: false,
      name: 'birthDate',
      label: 'Date de naissance',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'phoneNumber',
      label: 'Numéro de téléphone',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 6,
      desktopOrder: 6,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'email',
      label: 'Adresse e-mail',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.singleselection,
      disabled: false,
      name: 'gender',
      label: 'Gendre',
      value: '',
      options: ['Male', 'Female', 'Other'],
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.numberbox,
      disabled: false,
      name: 'cin',
      label: 'Numéro CIN',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 9,
        maxLength: 9,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'address',
      label: 'Adresse personnelle',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'vile',
      label: 'Ville',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'postal',
      label: 'Code postal',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'adresseEntreprise',
      label: 'Nom de lentreprise',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'adresseEntreprise',
      label: 'Adresse de l entreprise',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'tva',
      label: 'Numero de TVA',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee du CIN recto verso ',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee du RNE',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

 
    {
      type: FieldType.checkbox,
      disabled: false,
      name: 'conditions_generales',
      label: `Je reconnais avoir lu <a href=""> les conditions générales d'utilisation</a> et les accepte, <a href=""> la politique de protection</a> des données et consent au traitement de mes données dans le cadre du service`,
      value: false,
      successValue: true,
      failValue: false,
      width: '100%',
      mobileWidth: '100%',
      mobileOrder: 15,
      desktopOrder: 15,
      flex: {
        direction: 'row',
      },
    
    },
  ],
};
export const SIGN_UP_PRESTATAIRE_PARPHARMACIE: DynamicForm = {
  hasFiles: false,
  fields: [
    {
      type: FieldType.input,
      disabled: false,
      name: 'firstname',
      label: 'Nom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 3,
      desktopOrder: 3,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'lastname',
      label: 'Prénom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 4,
      desktopOrder: 4,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },

    {
      type: FieldType.datepicker,
      disabled: false,
      name: 'birthDate',
      label: 'Date de naissance',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'phoneNumber',
      label: 'Numéro de téléphone',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 6,
      desktopOrder: 6,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'email',
      label: 'Adresse e-mail',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.singleselection,
      disabled: false,
      name: 'gender',
      label: 'Gendre',
      value: '',
      options: ['Male', 'Female', 'Other'],
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.numberbox,
      disabled: false,
      name: 'cin',
      label: 'Numéro CIN',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 9,
        maxLength: 9,
      },
    },
   
    {
      type: FieldType.input,
      disabled: false,
      name: 'address',
      label: 'Adresse personnelle',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'vile',
      label: 'Ville',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'postal',
      label: 'Code postal',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },


    {
      type: FieldType.input,
      disabled: false,
      name: 'nom',
      label: 'nom de l enteprise',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'adresseEntreprise',
      label: 'Adresse de l enteprise',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'tva',
      label: 'Numero de TVA',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee du CIN recto verso ',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee du RNE',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

 
    {
      type: FieldType.checkbox,
      disabled: false,
      name: 'conditions_generales',
      label: `Je reconnais avoir lu <a href=""> les conditions générales d'utilisation</a> et les accepte, <a href=""> la politique de protection</a> des données et consent au traitement de mes données dans le cadre du service`,
      value: false,
      successValue: true,
      failValue: false,
      width: '100%',
      mobileWidth: '100%',
      mobileOrder: 15,
      desktopOrder: 15,
      flex: {
        direction: 'row',
      },
    
    },
  ],
};

export const SIGN_UP_PRESTATAIRE_MAISONRETRAITE: DynamicForm = {
  hasFiles: false,
  fields: [
    {
      type: FieldType.input,
      disabled: false,
      name: 'firstname',
      label: 'Nom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 3,
      desktopOrder: 3,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'lastname',
      label: 'Prénom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 4,
      desktopOrder: 4,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },

    {
      type: FieldType.datepicker,
      disabled: false,
      name: 'birthDate',
      label: 'Date de naissance',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'phoneNumber',
      label: 'Numéro de téléphone',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 6,
      desktopOrder: 6,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'email',
      label: 'Adresse e-mail',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.singleselection,
      disabled: false,
      name: 'gender',
      label: 'Gendre',
      value: '',
      options: ['Male', 'Female', 'Other'],
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.numberbox,
      disabled: false,
      name: 'cin',
      label: 'Numéro CIN',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 9,
        maxLength: 9,
      },
    },
   
    {
      type: FieldType.input,
      disabled: false,
      name: 'address',
      label: 'Adresse personnelle',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'vile',
      label: 'Ville',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'postal',
      label: 'Code postal',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },


    {
      type: FieldType.input,
      disabled: false,
      name: 'nom',
      label: 'nom de l enteprise',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'adresseEntreprise',
      label: 'Adresse de l enteprise',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'tva',
      label: 'Numero de TVA',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee du CIN recto verso ',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee du RNE',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

 
    {
      type: FieldType.checkbox,
      disabled: false,
      name: 'conditions_generales',
      label: `Je reconnais avoir lu <a href=""> les conditions générales d'utilisation</a> et les accepte, <a href=""> la politique de protection</a> des données et consent au traitement de mes données dans le cadre du service`,
      value: false,
      successValue: true,
      failValue: false,
      width: '100%',
      mobileWidth: '100%',
      mobileOrder: 15,
      desktopOrder: 15,
      flex: {
        direction: 'row',
      },
    
    },
  ],
};
export const SIGN_UP_PRESTATAIRE_LABORATOIRES: DynamicForm = {
  hasFiles: false,
  fields: [
    {
      type: FieldType.input,
      disabled: false,
      name: 'firstname',
      label: 'Nom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 3,
      desktopOrder: 3,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'lastname',
      label: 'Prénom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 4,
      desktopOrder: 4,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },

    {
      type: FieldType.datepicker,
      disabled: false,
      name: 'birthDate',
      label: 'Date de naissance',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'phoneNumber',
      label: 'Numéro de téléphone',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 6,
      desktopOrder: 6,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'email',
      label: 'Adresse e-mail',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.singleselection,
      disabled: false,
      name: 'gender',
      label: 'Gendre',
      value: '',
      options: ['Male', 'Female', 'Other'],
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.numberbox,
      disabled: false,
      name: 'cin',
      label: 'Numéro CIN',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 9,
        maxLength: 9,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'ordre',
      label: `Indentifiant d l'ordre des médecinsordre`,
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'address',
      label: 'Adresse',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'vile',
      label: 'Ville',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'postal',
      label: 'Code postal',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'adresseEntreprise',
      label: 'Adresse de lentreprise',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'tva',
      label: 'Numero de TVA',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee du CIN recto verso ',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee du RNE',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.radiobuttons,
      disabled: false,
      name: 'inscritCnam',
      label: 'Etes vous inscrit dans l CNAM',
      value: '',
      placeholder: '',
      width: '100%',
      options: ['oui', 'non', ],
      mobileWidth: '100%',
      mobileOrder: 1,
      desktopOrder: 1,
      flex: {
        direction: 'row',
      },
    },

    {
      type: FieldType.checkbox,
      disabled: false,
      name: 'conditions_generales',
      label: `Je reconnais avoir lu <a href=""> les conditions générales d'utilisation</a> et les accepte, <a href=""> la politique de protection</a> des données et consent au traitement de mes données dans le cadre du service`,
      value: false,
      successValue: true,
      failValue: false,
      width: '100%',
      mobileWidth: '100%',
      mobileOrder: 15,
      desktopOrder: 15,
      flex: {
        direction: 'row',
      },
    
    },
  ],
};
export const SIGN_UP_PRESTATAIRE_BABYSITTING: DynamicForm = {
  hasFiles: false,
  fields: [
    {
      type: FieldType.radiobuttons,
      disabled: false,
      name: 'type',
      label: '',
      value: '',
      placeholder: '',
      width: '100%',
      options: [
        'infirmier(e)',
        'Ausilisire de vie',
        'Aide soignante',
     
      ],
      mobileWidth: '100%',
      mobileOrder: 1,
      desktopOrder: 1,
      flex: {
        direction: 'row',
      },
    },
    {
      type: FieldType.radiobuttons,
      disabled: false,
      name: 'type',
      label: '',
      value: '',
      placeholder: '',
      width: '100%',
      options: [
     
        'Technicien de réanimatin',
        'Kinésithérapeute',
      ],
      mobileWidth: '100%',
      mobileOrder: 2,
      desktopOrder: 2,
      flex: {
        direction: 'row',
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'firstname',
      label: 'Nom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 3,
      desktopOrder: 3,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'lastname',
      label: 'Prénom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 4,
      desktopOrder: 4,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },

    {
      type: FieldType.datepicker,
      disabled: false,
      name: 'birthDate',
      label: 'Date de naissance',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'phoneNumber',
      label: 'Numéro de téléphone',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 6,
      desktopOrder: 6,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'email',
      label: 'Adresse e-mail',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.singleselection,
      disabled: false,
      name: 'gender',
      label: 'Gendre',
      value: '',
      options: ['Male', 'Female', 'Other'],
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.numberbox,
      disabled: false,
      name: 'cin',
      label: 'Numéro CIN',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 9,
        maxLength: 9,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'photo',
      label: 'Photo a vous',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'address',
      label: 'Adresse',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'vile',
      label: 'Ville',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },
    
    {
      type: FieldType.input,
      disabled: false,
      name: 'postal',
      label: 'Code postal',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'fonction',
      label: 'Fontion actuel',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'copiecin',
      label: 'copie scannee de CIN recto verso',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
  

  
  
    {
      type: FieldType.checkbox,
      disabled: false,
      name: 'conditions_generales',
      label: `Je reconnais avoir lu <a href=""> les conditions générales d'utilisation</a> et les accepte, <a href=""> la politique de protection</a> des données et consent au traitement de mes données dans le cadre du service`,
      value: false,
      successValue: true,
      failValue: false,
      width: '100%',
      mobileWidth: '100%',
      mobileOrder: 15,
      desktopOrder: 15,
      flex: {
        direction: 'row',
      },
    
    },
  ],
};
export const SIGN_UP_PRESTATAIRE_POMPFUNEBRE: DynamicForm = {
  hasFiles: false,
  fields: [
    {
      type: FieldType.input,
      disabled: false,
      name: 'firstname',
      label: 'Nom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 3,
      desktopOrder: 3,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'lastname',
      label: 'Prénom',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 4,
      desktopOrder: 4,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 3,
        maxLength: 20,
      },
    },

    {
      type: FieldType.datepicker,
      disabled: false,
      name: 'birthDate',
      label: 'Date de naissance',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'phoneNumber',
      label: 'Numéro de téléphone',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 6,
      desktopOrder: 6,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'email',
      label: 'Adresse e-mail',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.singleselection,
      disabled: false,
      name: 'gender',
      label: 'Gendre',
      value: '',
      options: ['Male', 'Female', 'Other'],
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.numberbox,
      disabled: false,
      name: 'cin',
      label: 'Numéro CIN',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 5,
      desktopOrder: 5,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        minLength: 9,
        maxLength: 9,
      },
    },
   
    {
      type: FieldType.input,
      disabled: false,
      name: 'address',
      label: 'Adresse personnelle',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'vile',
      label: 'Ville',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 7,
      desktopOrder: 7,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
        email: true,
      },
    },

    {
      type: FieldType.input,
      disabled: false,
      name: 'postal',
      label: 'Code postal',
      value: '',
      placeholder: '',
      width: '25%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },


    {
      type: FieldType.input,
      disabled: false,
      name: 'nom',
      label: 'nom de l enteprise',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 8,
      desktopOrder: 8,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'adresseEntreprise',
      label: 'Adresse de l enteprise',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.input,
      disabled: false,
      name: 'tva',
      label: 'Numero de TVA',
      value: '',
      placeholder: '',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 10,
      desktopOrder: 10,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee du CIN recto verso ',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },
    {
      type: FieldType.inputuploade,
      disabled: false,
      name: 'filediplome',
      label: 'copie scannee du RNE',
      value: '',
      placeholder: 'file',
      width: '50%',
      mobileWidth: '100%',
      mobileOrder: 12,
      desktopOrder: 12,
      flex: {
        direction: 'row',
      },
      rules: {
        required: true,
      },
    },

 
    {
      type: FieldType.checkbox,
      disabled: false,
      name: 'conditions_generales',
      label: `Je reconnais avoir lu <a href=""> les conditions générales d'utilisation</a> et les accepte, <a href=""> la politique de protection</a> des données et consent au traitement de mes données dans le cadre du service`,
      value: false,
      successValue: true,
      failValue: false,
      width: '100%',
      mobileWidth: '100%',
      mobileOrder: 15,
      desktopOrder: 15,
      flex: {
        direction: 'row',
      },
    
    },
  ],
};
