export enum FieldType {
    input = 'input',
    timepicker = 'timepicker',
    textbox = 'textbox',
    textarea = 'textarea',
    numberbox = 'numberbox',
    dropdown = 'dropdown',
    radiobuttons = 'radiobuttons',
    checkbox = 'checkbox',
    datepicker = 'datepicker',
   ceremoniefuneraire ='ceremoniefuneraire',
    daterangepicker = 'daterangepicker',
    chips = 'chips',
    singleselection = 'singleselection',
    multiselection = 'multiselection',
    iconpicker = 'iconpicker',
    upload = 'upload',
    inputuploade='inputuploade',
    text = 'text',
    password = 'password',
    custom = 'custom',
    
}