import { Location } from "@models/location.model";

export interface RegisterReqDTO {
  age?: number,
  email?: string,
  password?: string,
  confirmPassword?: string,
  phoneNumber?: number,
  Verified?: boolean,
  location?: Location,
  role?: string,
  firstname?: string,
  lastname?: string,
  birthDate?: string,
  gender?: string,
  cin?: number,
  allergie?: string,
  occupe?: boolean,
  city?: string,
  postal?: number,
  address?: string,
  id_om?: string,
  experience?: number,
  actualFunction?: string,
  companyName?: string,
  companyAdress?: string,
  tva?: string,
  cin_Pics?: File[],
  om_Pic?: File[],
  prestataire?: boolean,
  profilePhoto?: File,
  b3Pic?: File,
  rnePhoto?: File,
  ableToDo?: boolean
}
